name: Skanada
version: '1.2'
main: net.outmoded.skanada.Skanada
api-version: '1.21'
depend: [Skript]
author: KuraiSkrap and DRAGNIL68
description: a collection of random skript utility's for the maple syrup enjoyers